### ISSUE TITLE
VM ip address not accessible, not the same subnet mask

### ISSUE THREAD

**Issue by hoavt** [teracyhq/dev#234]
The problem happens on mac
- vagrant up
- vagrant ssh
- cd workspace/teracy-dev/docs
- review PR of others

Actual outcome: the IP address is not accessible and cannot review the docs, the subnet mask is not the same
Expected: The subnet mask should be the same 

@hoatle knew the bug

**Comment by hoatle** [comment]
@hoavt please re-check if you can re-produce the problem with teracy-dev v0.5.0-c1? If not, let's close this.

**Comment by hoavt** [comment]
Cannot reproduce.
