### ISSUE TITLE
should update the git setup docs to connect with github

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#270]
should add more details, refer to: https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by hoavt** [comment]
the  help github is very clear and detailed, I don't think we need to add more details. Just need to update the link in the docs.

**Comment by hoatle** [comment]
setting up on windows + cygwin is slightly different, make sure users from Cygwin can follow step by step.

Moreover, this is very important if someone has already setting ssh keys with git bash. Need to emphasize that git bash should be used, using git on cygwin only to prevent a lof of problems related to new line and file mode problems.

**Comment by phuonglm** [comment]
verified, close
