### ISSUE TITLE
custom vagrantfile

### ISSUE THREAD

**Issue by ducva** [teracyhq/dev#301]
Mình muốn custom file vagrant để có thể setup sẵn một số package cũng như software cho project cụ thể.

Bạn có thể hướng dẫn mình được không?

**Comment by hoatle** [comment]
Mặc định teracy-dev cùng Chef provisioner để cài đặt các packages lên VM.

Cách config thì tương tự https://github.com/teracyhq/dev/blob/master/vagrant_config.json#L89 nếu bạn dùng Chef.

Ngoài ra thì bạn có thể dùng các provisioner khác theo như ở đây: https://www.vagrantup.com/docs/provisioning/

teracy-dev hỗ trợ config override toàn bộ các provisioner được vagrant support.

Ví dụ như muốn đăng ký thêm bash provisioner thì vagrant_config_override.json có đoạn kiểu như:
```
{
  "provisioners": [{
    "_id": "1",
    "type" => "shell",
    "name" => "test",
    "path" => "<path_to>/test.sh"
  }]
}
```

Về cơ bản sẽ là vậy, đây là advanced feature bên mình sẽ update cho nó sớm. Để customize VM tốt thì cần nắm vững được vagrant, các provisioner tool rồi config cho nó phù hợp.

isssue liên quan: https://github.com/teracyhq/dev/issues/279

**Comment by ducva** [comment]
Ok. Minh hieu roi
