### ISSUE TITLE
should have CLA guide and contributors must sign before we could accept their contribution

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#306]
Some related links to study:

https://cla.github.com/
https://cla-assistant.io/ https://github.com/cla-assistant/cla-assistant
https://github.com/clabot/clabot
https://github.com/clahub/clahub

**Comment by hoatle** [comment]
https://cla-assistant.io/ looks good to me, let's try it.

**Comment by hoatle** [comment]
this is the "contribution license agreement" copied and adapted from https://cla.github.com/agreement https://gist.github.com/hoatle/47f23d2020f86e6529840998276568a7

**Comment by hoatle** [comment]
the workflow was tested, looks good: https://github.com/teracyhq/dev/pull/345
from now on, everyone must sign the CLA instructed and checked by the bots so that we can accept the contribution.

**Comment by hoatle** [comment]
this issue is under reviewing by our lawyer to check if there is any problem with this.

**Comment by doanhlaw** [comment]
Hi @hoale,
I'm here. I will check CLA ASAP.

**Comment by hoatle** [comment]
moved out of v0.5.0-c1 to v0.5.0-c2 so that @doanhlaw could have more time to validate this.

**Comment by doanhlaw** [comment]
@hoatle I've modified and added this Agreement. Please check Trello card: https://trello.com/c/s5RoAWS2

**Comment by hoatle** [comment]
@doanhlaw thank you, I'll check that soon.

**Comment by hoatle** [comment]
done, closed.
