### ISSUE TITLE
should update docs how to have internet access to local dev applications via Ngrok

### ISSUE THREAD

**Issue by phuonglm** [teracyhq/dev#308]
Some time dev need to expose their app to outside to make demo, we need have guide/tool for:
SSH forward from teracy-dev to public server ( require ssh credential )
Ngrok ( free, opensource ) secure tunnel from Ngrokd server to local port.

**Comment by hoatle** [comment]
we can't make it for v0.5.0-c1 so moved to v0.5.0-c2 instead.

**Comment by hoatle** [comment]
we really need this for web hooks related tasks now.

**Comment by hoatle** [comment]
it's recommended to use the Ngrok docker container that connects to the existing nginx-proxy container from teracy-dev.

**Comment by hoatle** [comment]
this is very critical and important for us to test CI services on local dev which require web hooks.

**Comment by hoatle** [comment]
assigned back to me as I'm working on this for drone.io local dev.

**Comment by hoatle** [comment]
see:
- https://github.com/acme101/ror-starter/pull/17
- https://github.com/acme101/ror-starter/issues/15

So it's ok to use Ngrok for now, we don't have to update anything with teracy-dev. We'll update the docs later.

**Comment by hoatle** [comment]
closed as this is possible to extend teracy-dev for v0.6.0
