### ISSUE TITLE
should have info with action to do when config changes

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#318]
sometimes, config changes require $ vagrant destroy and $ vagrant up

sometimes, $ vagrant reload --provision is enough or sometimes $ vagrant reload is required for new updated config.

Currently, we do this very manually by asking everyone to update the config and do associated actions.

This is not good.

We should find a way to inform users automatically with actions to do.

Do do this, teracy-dev must keep track of changes (by revision for example and inform users about the corresponding actions do to)

**Comment by hoatle** [comment]
by this, we can inform users about anything, for example, to upgrade teracy-dev version.

All of these are controlled by users with vagrant config files.

**Comment by phuonglm** [comment]
We can use .bashrc to check version upgrade of teracy-dev, child project and notification.
for tracking config change we can merge all config file, save it and compare it in .bashrc, there's 3 config type, initial for first vagrant up, current for last provision run, and code for current config in code.
Just 3 problems are:
 + How we can run merge config ( for current config in code ) in .bashrc before compare it.
 + How we know which config need to be full reload or just provision is enough
 + What about other updates (change in recipe, code sometimes need full provision too).

**Comment by hoatle** [comment]
https://www.vagrantup.com/docs/triggers/ could be helpful for this

**Comment by hoatle** [comment]
this is an extended feature that is possible for v0.6.0, closed for now, we'll see if extension is mature and useful enough to bring into core. I don't think we'll bring this into core.
