### ISSUE TITLE
Should support IP keeping when vagrant destroy and up again

### ISSUE THREAD

**Issue by phuonglm** [teracyhq/dev#325]
Vagrant keeps asking about bridge interface and change IP address every time it reprovisions. Need update Vagrantfile to ask user want to save that and reuse that file every time it starts.

**Comment by hoatle** [comment]
related: https://github.com/teracyhq/dev/issues/271

**Comment by hoatle** [comment]
let's see if the implementation is stable enough to be included into v0.5.0

**Comment by phuonglm** [comment]
relate #274

**Comment by hoatle** [comment]
there could be issues when users switch networks, so make sure to include this use case.

Current behavior is that users should `$ vagrant reload` when networks are switched (from LAN to wifi or to other networks).

**Comment by phuonglm** [comment]
for Linux, macos execute this command for getting default interface
Linux:
`route | grep '^default' | grep -o '[^ ]*$'`
Macos
`route -n get 8.8.8.8 | grep interface | awk '{print $2}'`

Not windows yet

**Comment by hoatle** [comment]
this requires intensive testing with different scenarios, @phuonglm please list different scenarios for testing. When all the scenarios are passed, we can introduce this improvement to v0.5.0-c2.

**Comment by hoatle** [comment]
verified, closed.

**Comment by hoatle** [comment]
sorry, this did not work with my Ubuntu. Everytime I destroy and created a new VM, a new ip is granted to the VM. It's expected that the same ip should be used.

**Comment by hoatle** [comment]
the same with my Mac, something wrong with the code changes I guess.

**Comment by hoatle** [comment]
rechecked, it works, sorry 💃
