### ISSUE TITLE
Bug: Next button is not working when installing bash-completion

### ISSUE THREAD

**Issue by hoavt** [teracyhq/dev#327]
At Step "Install bash-completion" with the command  `$ cyg-get.bat bash-completion`, the set up window is show, but it cannot move to Next step, so installing bash-completion cannot be completed.

**Comment by hoatle** [comment]
the root cause is that we did not pin the installed version and this could possibly cause problems in the future. So we need to check and use the most stable versions of cygwin and cyg-get.

Workaround available if anyone has the same problem:

```
choco install cygwin --version 2.8.0 -y --ignore-checksums
choco install cyg-get --version 1.2.1 -y
```

**Comment by phuonglm** [comment]
verified, close
