### ISSUE TITLE
failed to choco install vagrant on Windows 7 due to .NET version problem

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#348]
Need to install .NET v4.5 on Windows 7 after installing choco.

Should mention on docs that sometimes users need to hit "Enter" key when the terminal does not send console output after some time (looks like freeze, just press "Enter" key for it to continue)

install choco => restart
install dotnet4.5 => restart
install vagrant => restart

**Comment by hoatle** [comment]
seems that @phuonglm had a different idea about the root cause and solution, assigned to @phuonglm to spend more time on this to find out the possibly "true" root cause and solution.

**Comment by hoatle** [comment]
root cause from .NET version: http://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/ and the choco downloader uses .NET to download.

vagrant site supports SLv3 and TLS 1.0, so we need to upgrade .NET to at least v4.5 to make the downloader works.

**Comment by phuonglm** [comment]
verified, close
