### ISSUE TITLE
Should allow user to know the version number of teracy-dev

### ISSUE THREAD

**Issue by hoavt** [teracyhq/dev#366]
```hieptq [4:23 PM] 
a ơi! check cái số version ở đâu ạ >“< chị Hoa hỏi e ạ


[4:23] 
hình như là cái semver thì phải


[4:23] 
e chỉ biết check đối chiếu với repo


[4:23] 
bằng git log


[4:23] 
và git branch thôi ạ


[4:24] 
ko biết câu lệnh để lấy ra cái số version là gì ạ


hoatle [4:25 PM] 
ừ, em hướng dẫn chị @hoavt xem có làm được không, hiện tại thì dùng git branch và git log để check


hieptq [4:25 PM] 
dạ em hướng dẫn  rồi ạ


[4:25] 
chị ấy đòi lấy cái số


new messages
[4:25] 
thì e ko biết


[4:26] 
e bảo chị ấy check theo git, xem những thông tin từ git repo ở local là biết (git branch, git log rồi đối chiếu với remote repo)


hoatle [1 minute ago] 
hiện tại thì dựa vào git info chưa lấy được số cụ thể version đâu bạn @hoavt, nên tạo issue để in ra đúng version của teracy-dev mà user đang dùng (edited)```

**Comment by hoatle** [comment]
I guess `$ vagrant teracy-dev version` should display all the information of the current teracy-dev.

For example:

```
$ vagrant teracy-dev version
teracy-dev v0.5.0, build c7bdf9e
```

**Comment by phucvdb** [comment]
After investigating this issue, I think we can solve this issue by 04 below options:
1. Create vagrant box for teracy dev --> we can manage version of teracy dev via version of vagrant box
2. check version via git
 using  ```git describe --tags --abbrev=0```
3. Create a new vagrant plugin for project to show git tag
4. Develop new command of teracy dev (e.g: teracy dev version)

I suggest to implement option #2(using git command).
 
Please consider the above options with your expectation and fix what is best option for next steps? Or if you have other solution, let me know. @hoatle @phuonglm

**Comment by phuonglm** [comment]
As discussed on Slack with @hoatle time ago and @phucvdb I thought `git describe --tags --abbrev=0` couldn't detect when a tag had an update/hotfix and it also doesn't give you right information when you on develop branch. 

`git describe --tags` can give you which tag and how many commits difference from that tag you currently on plus commit hash. That probably gives you enough information user need to check version ie. 
```
phuonglm@:~/Projects/iorad/iorad-dev$ git describe --tags
v0.5.0-c1-33-g1dd0605
```
Means 33 commit ahead of 0.5.0-c3  with hash g1dd0605

About mechanism, a plugin could be good but to be simple just check a second argument (`puts ARGV[0]`) of `vagrant *` command if that argument is `up` or `ssh`, `version` cheer them with a nice message about version info of teracy-dev. That would be enough for me.

PS: the version must be unified between showing to user and document generate so if we apply the then we need to change https://github.com/teracyhq/dev/blob/master/docs/conf.py#L57 and the way we make a release.
WDYT @hoatle

**Comment by hoatle** [comment]
```About mechanism, a plugin could be good but to be simple just check a second argument (puts ARGV[0]) of vagrant * command if that argument is up or ssh, version cheer them with a nice message about version info of teracy-dev. That would be enough for me.``` => good to me, so that everytime users use `$ vagrant up` or `$ vagrant ssh`, we display teracy-dev's version info.

PS part: go for it, too :-)

**Comment by hoatle** [comment]
@phucvdb let us know if that's clear enough to implement then.

**Comment by phucvdb** [comment]
I have tried to do something and below is my output:

```phucv@DESKTOP-QJPVM7P ~/teracy-dev
$ vagrant.exe up
[info] Teracy-dev version 0.5.0-c1```

```phucv@DESKTOP-QJPVM7P ~/teracy-dev
$ vagrant.exe ssh
[info] Teracy-dev version 0.5.0-c1```

about idea relates to "version" arg, i have no idea, because when i try:

1. vagrant version
2. vagrant teracydev version

the output shows some introduction for vagrant.exe command. something like as following:
```phucv@DESKTOP-QJPVM7P ~/teracy-dev
$ vagrant.exe version
Installed Version: 1.9.1
Latest Version: 2.0.1

To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/mitchellh/vagrant/blob/v2.0.1/CHANGELOG.md
[info] Teracy-dev version 0.5.0-c1```

finally, i think we can push some message about teracydev version when we run "vagrant up" and "vagrant ssh".

Please correct them is as your expectation or not @hoatle @phuonglm
