### ISSUE TITLE
Optimize virtual machine config for better performance

### ISSUE THREAD

**Issue by phuonglm** [teracyhq/dev#384]
On windows 7 64 bit, 8GB ram, I got huge performance improve (especially CPU IO wait time) when applied https://gist.github.com/irvingpop/04161a095dd616321322#file-sane_defaults-rb-L33 manually.  Please consider, test and apply these tweaks to our VM json config to improve VM performance.

here is the problem before tweak:
![screen shot 2017-07-31 at 7 55 12 am](https://user-images.githubusercontent.com/646429/28760951-598f1942-75d5-11e7-9bdb-6eaa1076ef99.png)
![screen shot 2017-07-31 at 7 56 59 am](https://user-images.githubusercontent.com/646429/28760952-5990175c-75d5-11e7-97d6-21ca63ce6996.png)

**Comment by hoatle** [comment]
@phuonglm and what's about the performance after the tweak?

**Comment by phuonglm** [comment]
the CPU IO wait goes down almost nothing. I was able to use the VM and `dmesg` error gone. Not fully profiling yet

**Comment by hoatle** [comment]
this is the extension feature, so close now.
