### ISSUE TITLE
should check and verify the fix for double webpack building trigger 

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#390]
```
ivanm376 [6:26 AM] 
maybe somebody also have question with double webpack building trigger on linux:
you need to edit `vagrant_config.json` and  add   *"rsync__chown": false,*    after  *"guest": "/home/vagrant/workspace",*
hoatle [5 minutes ago] 
thank you, let me check on this to update for all.
```

I guess that the problem is happening on all platforms, not just Linux.

**Comment by phuonglm** [comment]
disable chown in this case could lead to another . I think problem did not come from rsync because chown is necessary to make sure consistency in permission.
For this case please increase webpack aggregateTimeout to add a tiny delay.
https://webpack.js.org/configuration/watch/#watch

**Comment by hoatle** [comment]
@phuonglm does webpack's adjustment work?

**Comment by phuonglm** [comment]
I checked and it worked.
