### ISSUE TITLE
should improve logging by adding filter, tracing

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#444]
0. filter

Logging.add_filter(filter) api

logging/default_filter is added as following:
default_filter handle LOG_FILTER env var as the regular expressing to filter the `progname`
for example: LOG_FILTER=* by default => display all progname

before displaying the log message, filters are called, log message is displayed when all filters return true

1. tracing
every log message must have info of where the log is called (file, line number, function/method name and the message)

**Comment by hoatle** [comment]
@datphan this is what I meant to make it clearer, you can continue implementing it on this branch: https://github.com/hoatle/teracy-dev/tree/features/%23444-logging-filter

**Comment by datphan** [comment]
fixed: https://github.com/hoatle/teracy-dev/pull/7

**Comment by hoatle** [comment]
merged, tracing is not working yet, need to display the exact number of the file and the function name within which the logger is called

**Comment by hoatle** [comment]
moving this issue to v0.6.0-a3
