### ISSUE TITLE
should support register processors, configurators with weight

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#497]
Currently, FIFO is applied.

Now we're going to have weight and FIFO.
- weight: int (0-9), default: 5 => the more weight, the associated item will be called first. If the same weight => FIFO is applied.

This is a backward compatible change.

APIs signature:

TeracyDev.register_processor(processor, weight=5)
TeracyDev.register_configurator(configurator, weight=5)

By supporting this, extensions can have a chance to control the calling order of processors, configurators.

**Comment by hieptranquoc** [comment]
@hoatle Why do not we allow set `weight` in `config.yaml`, but only allow weight in `TeracyDev.register_processor(processor, weight=5)`. I think we should set `weight` in config.yaml. How do you think?

**Comment by hoatle** [comment]
Currently, we support only Ruby code to register, even using yaml config, ruby api code still needs the changes I mentioned above

**Comment by hieptranquoc** [comment]
@hoatle I mean, we can sort the `config.yaml`, before teracy-dev build settings from `config.yaml`

**Comment by hoatle** [comment]
No, that’s not what I see and understand.
