### ISSUE TITLE
should upgrade packages on getting started docs

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#511]
Some packages are not up to date, we need to upgrade to the latest stable working packages.

Devs will upgrade then QAs will verify.

docs: https://github.com/teracyhq/dev/blob/develop/docs/getting_started.rst

**Comment by hoatle** [comment]
- vagrant: >= 2.1.0 https://github.com/teracyhq/dev/blob/develop/system.yaml#L3
- virtualbox: >= 5.2 https://github.com/teracyhq-incubator/teracy-dev-core/blob/develop/config.yaml#L53

others: should use the latest stable working version

**Comment by hoatle** [comment]
assigned to @hoavt to verify the getting started docs

**Comment by hoavt** [comment]
confirmed
