### ISSUE TITLE
logger should be `TeracyDev::Config::Manager` instead of `TeracyDev::Processors::Manager`

### ISSUE THREAD

**Issue by hieptranquoc** [teracyhq/dev#514]
https://github.com/teracyhq/dev/blob/fafdef06cefc319457b1e0d92036cfdc33a98c27/lib/teracy-dev/config/manager.rb#L11

**Comment by hieptranquoc** [comment]
fixed in #497 , and I created PR #512 !

**Comment by hoatle** [comment]
@hieptranquoc please creat separated PR for each issue

**Comment by hoatle** [comment]
fixed in #497
