### ISSUE TITLE
Fail to sync with git version 2.7.4

### ISSUE THREAD

**Issue by phuonglm** [teracyhq/dev#516]
While checking with git.location.remote feature, I got this issue with git version 2.7.4. 
```
[TeracyDev::Location::GitSynch][WARN]: `/home/phuonglm/Projects/teracy/dev/lib/../extensions/teracy-dev-core` has untracked changes, auto update is aborted!
 HEAD detached at v0.3.0
nothing to commit, working directory clean
```
I guess git_stage_has_untracked_changes was wrong with this grep `'nothing to commit, working directory clean'`

**Comment by hoatle** [comment]
note: there is a case that could be a bug for the way of checking: users make changes and commit.
