### ISSUE TITLE
should check to make sure teracy-dev works well with virtualbox 6.0

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#600]
on macOS, Linux, Windows

**Comment by hieptranquoc** [comment]
@hoatle I am using VirtualBox 6.0 since the day it was released and no matter what happens!

**Comment by hoatle** [comment]
note on Ubuntu, after upgrading to virtualbox 6.0, I got the following error:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "a9f55917-e3fd-4710-bd5d-7a63fdb0c693", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'teracy-dev_node-01_1548166120359_62957' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

I had to execute `$ sudo /sbin/vboxconfig` to get it work, see: https://stackoverflow.com/questions/37312334/error-on-vagrant-up-on-linux

**Comment by hoatle** [comment]
so basically, it works with my check on Ubuntu (16.04) and macOS Mojave.

need to check and confirm on Windows.

**Comment by hieptranquoc** [comment]
Confirm it works well on Windows!
